### PR TITLE
fix grouping by of different languages scores

### PR DESCRIPTION
**Pull request by OfirArviv**
See https://stackoverflow.com/questions/8116666/itertools-groupby-not-grouping-correctly

### CODE REVIEW

**Comment by danielhers** [comment]
I actually liked that I could give several test subsets and see them separately (even if they're in the same language) when I didn't specify them contiguously, i.e. when I ran `tupa wiki_en 20k_fr 20k_de 20k_en`. But I agree that this is not the clearest behavior. Do you have a use case where you prefer to see them together? That is, when you give files of different formats and languages mixed rather than listing them one after the other as arguments?

About the diff itself, better extract the key function to a named function (with `def`) instead of `lambda`.
And it's not just by language, it's also by format (e.g., UCCA/AMR/SDP/CoNLL-U) -- this is the primary sorting key (`type(...)`).

**Comment by OfirArviv** [comment]
Oh.. than it might be ok.
I put all the English, French and German xml in the same directory and got a problem of not having the language separated correctly (I got something like en, de, fr, de, fr, en). So I thought its a bug.
If I have put them in separate directory, it wouldn't have happened?
If that so, I would suggest not having a groupby at all if its in the same directory, because right now the behavior of the gorupby is erroneous in the scenario of same directory.

**Comment by danielhers** [comment]
Yes, if you put them in separate directories then they won't be mixed.
But I get why this can be called a bug...

Den lør. 1. jun. 2019 kl. 22.15 skrev OfirArviv <notifications@github.com>:

**Comment by OfirArviv** [comment]
So I wouldn't approve this PR, but think you should think of a different behavior that still gives you the flexibility you want and maintain correctness. I'm not sure how the code behave when having different directories... so not sure what the solution is. But probably its something along the lines of keeping the directories separate and have the sort and groupby operation on each dir seperately or not having them at all.

**Pull request closed without merging**
